name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        ruby:
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - 'head'
        gemfile:
          - 'gemfiles/Gemfile.faraday-0.x'
          - 'gemfiles/Gemfile.faraday-1.x'
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}
    name: Run test with Ruby ${{ matrix.ruby }}, ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rspec
